name: Build

on: 
  push:
      branches:
      - 'main'

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.2.0
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: yarn --cwd ./docs
      - name: Generate
        run: yarn run --cwd="./" build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: 1host.js.org
